### ISSUE TITLE
The program is not efficient

### ISSUE THREAD

**Issue by mustafahdurmaz** [AktugHakan/NinovaArsivci#11]
Every time I run the program, it takes a lot of time to download the whole ninova again. Instead, it may be a more effective way to identify and download only newly added files with the help of database. We will also distinguish the newly added files.

OS: Windows 11
Version: Nightly

**Comment by IsE333** [comment]
> Every time I run the program, it takes a lot of time to download the whole ninova again. Instead, it may be a more effective way to identify and download only newly added files with the help of database. We will also distinguish the newly added files.
> 
> OS: Windows 11
> Version: Nightly

i do have the same problem too. Totally 300-400mb sized files are downloading everytime the program runs.

**Comment by AktugHakan** [comment]
It takes time to implement multiprocessing on different OS architectures, I will _temporarily_ disable the multiprocessing on Windows, threading will still work as before.

**Comment by mustafahdurmaz** [comment]
I expect you to share this update as soon as possible Sir.

**Comment by AktugHakan** [comment]
I fixed and shared the update, it is currently on Nightly branch.
