### ISSUE TITLE
"Veri tabanına manuel müdahele tespit edildi." hatası

### ISSUE THREAD

**Issue by IsE333** [AktugHakan/NinovaArsivci#13]
nightly branchinde hata alıyorum.
![image](https://user-images.githubusercontent.com/77530401/204371659-bc70e9e6-34ea-45fa-aff9-b48c6a81503a.png)
![image](https://user-images.githubusercontent.com/77530401/204371801-47a0ac74-d540-4df4-aba8-750ca8acde82.png)

**Comment by IsE333** [comment]
2. sefer çalıştırınca hata gitti

**Comment by AktugHakan** [comment]
Versiyon 2 ile indirilen bir klasör üzerinde versiyon 3 çalıştırılırsa bu hata geliyor ama aslında hata değil, upgrade yapıyor. Önemli bir durum değil ama hata mesajını kaldıracağım.

**Comment by AktugHakan** [comment]
Hata kaldırıldı
