### ISSUE TITLE
Eksik indirme sorunu

### ISSUE THREAD

**Issue by IsE333** [AktugHakan/NinovaArsivci#9]
Mat 143 dersinin dosyalarını indirmedi. diğer derslerde sorun yok. Bana da sadece 143 lazımdı. 2-3 defa arka arkaya çalıştırdım değişmedi.

**Comment by IsE333** [comment]
Bu sorun mainde yaşandı. Nightly düzgün çalıştı.
main 32sn (55mb)
nightly 67sn (320mb)

**Comment by AktugHakan** [comment]
Kod mimarisi ile iligili bazı düzenlemeler yaptım. Düzelmiş olmalı
